//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.WebUI.Resources.Views.ShoppingList {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Details_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Details_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shopping.WebUI.Resources.Views.ShoppingList.Details.uk", typeof(Details_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повернутися до списків.
        /// </summary>
        internal static string Back_to_Lists {
            get {
                return ResourceManager.GetString("Back to Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створено.
        /// </summary>
        internal static string Created_on {
            get {
                return ResourceManager.GetString("Created on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Existing_Users {
            get {
                return ResourceManager.GetString("Existing Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмети.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помітити як не куплено.
        /// </summary>
        internal static string Mark_as_Not_Purchased {
            get {
                return ResourceManager.GetString("Mark as Not Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помітити як куплено.
        /// </summary>
        internal static string Mark_as_Purchased {
            get {
                return ResourceManager.GetString("Mark as Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В цьому листі поки немає предметів.
        /// </summary>
        internal static string No_items_in_this_list_yet {
            get {
                return ResourceManager.GetString("No items in this list yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не куплено.
        /// </summary>
        internal static string Not_Purchased {
            get {
                return ResourceManager.GetString("Not Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куплено.
        /// </summary>
        internal static string Purchased {
            get {
                return ResourceManager.GetString("Purchased", resourceCulture);
            }
        }
    }
}
